% (C) Copyright 2020 CPP_BIDS developers

function trueOrFalse = isPositiveInteger(input2check)
    % trueOrFalse = isPositiveInteger(input2check)
    %
    % works on column vector of values
    %

    trueOrFalse = ~any([ ...
        ~isnumeric(input2check), ...
        isnan(input2check), ...
        fix(input2check) ~= input2check, ...
        input2check < 0 ...
        ]);

end
