function trueOrFalse = isPositiveInteger(input2check)
    
    trueOrFalse = ~(...
        ~isnumeric(input2check) || ...
        isnan(input2check) || ...
        fix(input2check) ~= input2check || ...
        input2check < 0);
    
end