---
name: BIDS validator

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  OCTFLAGS: --no-gui --no-window-system --silent

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Make jsonread for octave
      run: |
        sudo apt-get -y -qq update
        sudo apt-get -y install octave
        sudo apt-get -y install liboctave-dev
        cd lib/JSONio
        mkoctfile --mex jsonread.c jsmn.c -DJSMN_PARENT_LINKS
        cd ..

    - name: Update octave path
      run: |
        octave $OCTFLAGS --eval "addpath(pwd); savepath();"
        octave $OCTFLAGS --eval "addpath(genpath(fullfile(pwd, 'lib'))); savepath();"
        octave $OCTFLAGS --eval "addpath(genpath(fullfile(pwd, 'src'))); savepath();"

    - name: Install BIDS validator
      run: |
        sudo npm install -g bids-validator

    - name: Create dummy dataset and validate it
      run: |
        cd tests/manualTests
        octave $OCTFLAGS --eval "test_makeRawDataset"
        bids-validator `pwd`/output/raw/ --ignoreNiftiHeaders
